/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Sad(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sad.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="sad" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Rabbit001" geometry={nodes.Rabbit001.geometry} material={materials['Rabbit.001']} skeleton={nodes.Rabbit001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sad.glb')
