/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Happy(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/happy.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    actions.happy.play();
  },[]);

  return (
    <group ref={group} {...props} dispose={null} scale={[2,2,2]}>
      <group name="Scene">
        <group name="happy" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Rabbit" geometry={nodes.Rabbit.geometry} material={materials.Rabbit} skeleton={nodes.Rabbit.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/happy.glb')
